package com.baidaidai.rootless_store.components.pluginsScreen

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.tooling.preview.PreviewLightDark
import androidx.compose.ui.unit.dp
import com.baidaidai.rootless_store.R
import com.baidaidai.rootless_store.domain.pluginManiFest.model.PluginManiFest

@Composable
fun PluginInfosContainer(
    pluginManiFest: PluginManiFest,
    modifier: Modifier = Modifier
){
    val statusLabel = if (pluginManiFest.enabled) "Enabled" else "Disabled"
    val statusColor = if (pluginManiFest.enabled) {
        MaterialTheme.colorScheme.primary
    } else {
        MaterialTheme.colorScheme.error
    }
    Card(
        modifier = modifier
            .fillMaxWidth(),
        elevation = CardDefaults.cardElevation(),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceContainer
        )
    ){
        Column(
            modifier = Modifier
                .padding(24.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Row(
                modifier = Modifier
                    .fillMaxWidth(),
                verticalAlignment = Alignment.CenterVertically
            ){
                Icon(
                    painter = painterResource(R.drawable.outline_extension_24),
                    contentDescription = "Plugin Icon",
                    modifier = Modifier
                        .size(24.dp)
                )
                Spacer(
                    modifier = Modifier
                        .width(12.dp)
                )
                Column(
                    modifier = Modifier
                        .weight(1f)
                ){
                    Text(
                        text = pluginManiFest.name,
                        style = MaterialTheme.typography.titleMedium
                    )
                    Text(
                        text = "Version: ${pluginManiFest.installedVersion}",
                        style = MaterialTheme.typography.labelMedium
                    )
                }
                Text(
                    text = statusLabel,
                    style = MaterialTheme.typography.labelMedium,
                    color = statusColor
                )
            }
            HorizontalDivider()
            Column(
                verticalArrangement = Arrangement.spacedBy(6.dp)
            ) {
                PluginInfoRow(label = "Author", value = pluginManiFest.author)
                PluginInfoRow(label = "Source", value = pluginManiFest.source.toString())
                PluginInfoRow(label = "State", value = pluginManiFest.state.toString())
                PluginInfoRow(
                    label = "Required",
                    value = pluginManiFest.requiredEnvironment.toString()
                )
                PluginInfoRow(label = "Icon", value = pluginManiFest.iconURI)
            }
        }
    }
}

/**
 * Generated by Codex
 *
 * If Problems, Needs Review !
 */
@Composable
private fun PluginInfoRow(
    label: String,
    value: String,
    modifier: Modifier = Modifier
){
    Row(
        modifier = modifier
            .fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically
    ){
        Text(
            text = label,
            style = MaterialTheme.typography.bodyMedium,
            modifier = Modifier
                .weight(0.35f)
        )
        Text(
            text = value,
            style = MaterialTheme.typography.bodyMedium,
            modifier = Modifier
                .weight(0.65f)
        )
    }
}

@Composable
@PreviewLightDark
private fun _PluginInfosContainerPreview_(){
    PluginInfosContainer(PluginManiFest._testOnly_)
}
